---
apiVersion: v1
kind: Service
metadata:
  name: demo-web
  labels:
    app: demo
    role: web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo
    role: web
  type: ClusterIP
